export const Permissions = {
  USERS_CREATE: { code: 'users:create', group: 'users', description: 'Create new users' },
  USERS_READ: { code: 'users:read', group: 'users', description: 'View user details' },
  USERS_UPDATE: { code: 'users:update', group: 'users', description: 'Update user details' },
  USERS_DELETE: { code: 'users:delete', group: 'users', description: 'Delete users' },
  USERS_DEACTIVATE: { code: 'users:deactivate', group: 'users', description: 'Deactivate/activate users' },
  USERS_ASSIGN_ROLE: { code: 'users:assign-role', group: 'users', description: 'Assign roles to users' },
  STUDENTS_CREATE: { code: 'students:create', group: 'students', description: 'Create student records' },
  STUDENTS_READ: { code: 'students:read', group: 'students', description: 'View student records' },
  STUDENTS_UPDATE: { code: 'students:update', group: 'students', description: 'Update student records' },
  STUDENTS_DELETE: { code: 'students:delete', group: 'students', description: 'Delete student records' },
  STUDENTS_IMPORT: { code: 'students:import', group: 'students', description: 'Import student records' },
  STUDENTS_EXPORT: { code: 'students:export', group: 'students', description: 'Export student records' },
  CLEARANCE_CREATE: { code: 'clearance:create', group: 'clearance', description: 'Submit clearance requests' },
  CLEARANCE_READ: { code: 'clearance:read', group: 'clearance', description: 'View clearance requests' },
  CLEARANCE_APPROVE: { code: 'clearance:approve', group: 'clearance', description: 'Approve clearance' },
  CLEARANCE_REJECT: { code: 'clearance:reject', group: 'clearance', description: 'Reject clearance' },
  CLEARANCE_BULK_APPROVE: { code: 'clearance:bulk-approve', group: 'clearance', description: 'Bulk approve' },
  CLEARANCE_MANAGE_ALL: { code: 'clearance:manage-all', group: 'clearance', description: 'Manage all clearance' },
  DEPARTMENTS_CREATE: { code: 'departments:create', group: 'departments', description: 'Create departments' },
  DEPARTMENTS_READ: { code: 'departments:read', group: 'departments', description: 'View departments' },
  DEPARTMENTS_UPDATE: { code: 'departments:update', group: 'departments', description: 'Update departments' },
  DEPARTMENTS_DELETE: { code: 'departments:delete', group: 'departments', description: 'Delete departments' },
  COURSES_CREATE: { code: 'courses:create', group: 'courses', description: 'Create courses' },
  COURSES_READ: { code: 'courses:read', group: 'courses', description: 'View courses' },
  COURSES_UPDATE: { code: 'courses:update', group: 'courses', description: 'Update courses' },
  COURSES_DELETE: { code: 'courses:delete', group: 'courses', description: 'Delete courses' },
  CERTIFICATES_CREATE: { code: 'certificates:create', group: 'certificates', description: 'Generate certificates' },
  CERTIFICATES_READ: { code: 'certificates:read', group: 'certificates', description: 'View certificates' },
  CERTIFICATES_VERIFY: { code: 'certificates:verify', group: 'certificates', description: 'Verify certificates' },
  CERTIFICATES_DOWNLOAD: { code: 'certificates:download', group: 'certificates', description: 'Download certificates' },
  REPORTS_VIEW: { code: 'reports:view', group: 'reports', description: 'View reports' },
  REPORTS_GENERATE: { code: 'reports:generate', group: 'reports', description: 'Generate reports' },
  REPORTS_EXPORT: { code: 'reports:export', group: 'reports', description: 'Export reports' },
  ANALYTICS_VIEW: { code: 'analytics:view', group: 'analytics', description: 'View analytics' },
  ANALYTICS_EXPORT: { code: 'analytics:export', group: 'analytics', description: 'Export analytics' },
  SETTINGS_VIEW: { code: 'settings:view', group: 'settings', description: 'View system settings' },
  SETTINGS_UPDATE: { code: 'settings:update', group: 'settings', description: 'Update system settings' },
  AUDIT_VIEW: { code: 'audit:view', group: 'audit', description: 'View audit logs' },
  AUDIT_EXPORT: { code: 'audit:export', group: 'audit', description: 'Export audit logs' },
  NOTIFICATIONS_SEND: { code: 'notifications:send', group: 'notifications', description: 'Send notifications' },
  NOTIFICATIONS_READ: { code: 'notifications:read', group: 'notifications', description: 'Read notifications' },
  NOTIFICATIONS_MANAGE_TEMPLATES: { code: 'notifications:manage-templates', group: 'notifications', description: 'Manage templates' },
  ROLES_VIEW: { code: 'roles:view', group: 'roles', description: 'View role definitions' },
  ROLES_MANAGE: { code: 'roles:manage', group: 'roles', description: 'Manage role permissions' },
  QR_GENERATE: { code: 'qr:generate', group: 'qr', description: 'Generate QR codes' },
  QR_VERIFY: { code: 'qr:verify', group: 'qr', description: 'Verify QR codes' },
  EXAMS_VERIFY: { code: 'exams:verify', group: 'exams', description: 'Verify exam eligibility' },
  EXAMS_OVERRIDE: { code: 'exams:override', group: 'exams', description: 'Override eligibility' },
  BACKUP_CREATE: { code: 'backup:create', group: 'backup', description: 'Create backups' },
  BACKUP_RESTORE: { code: 'backup:restore', group: 'backup', description: 'Restore backups' },
  PROFILE_READ: { code: 'profile:read', group: 'profile', description: 'View own profile' },
  PROFILE_UPDATE: { code: 'profile:update', group: 'profile', description: 'Update own profile' },
  PROFILE_AVATAR: { code: 'profile:avatar', group: 'profile', description: 'Upload avatar' },
  PROFILE_CHANGE_PASSWORD: { code: 'profile:change-password', group: 'profile', description: 'Change own password' },
} as const;

export type PermissionCode = typeof Permissions[keyof typeof Permissions]['code'];

export const RolePermissions: Record<string, PermissionCode[]> = {
  SUPER_ADMIN: Object.values(Permissions).map(p => p.code),
  ADMINISTRATOR: [
    'users:create','users:read','users:update','users:deactivate','users:assign-role',
    'students:create','students:read','students:update','students:import','students:export',
    'clearance:read','clearance:manage-all',
    'departments:create','departments:read','departments:update','departments:delete',
    'courses:create','courses:read','courses:update','courses:delete',
    'certificates:create','certificates:read','certificates:verify','certificates:download',
    'reports:view','reports:generate','reports:export',
    'analytics:view','analytics:export',
    'settings:view','settings:update',
    'audit:view','audit:export',
    'notifications:send','notifications:read','notifications:manage-templates',
    'roles:view',
    'qr:generate','qr:verify',
    'exams:verify','exams:override',
    'backup:create','backup:restore',
    'profile:read','profile:update','profile:avatar','profile:change-password',
  ],
  REGISTRAR: [
    'students:create','students:read','students:update','students:import','students:export',
    'clearance:read',
    'departments:read',
    'courses:read',
    'certificates:create','certificates:read','certificates:download',
    'reports:view','reports:generate',
    'notifications:send','notifications:read',
    'exams:verify',
    'profile:read','profile:update','profile:change-password',
  ],
  FINANCE_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'reports:view',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  DEPARTMENT_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'departments:read','courses:read',
    'reports:view',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  LIBRARY_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  LABORATORY_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  SPORTS_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  HOSTEL_OFFICER: [
    'students:read',
    'clearance:read','clearance:approve','clearance:reject',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  LECTURER: [
    'students:read',
    'clearance:read',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  STUDENT: [
    'clearance:create','clearance:read',
    'certificates:read','certificates:download',
    'notifications:read',
    'profile:read','profile:update','profile:avatar','profile:change-password',
  ],
  PARENT: [
    'clearance:read',
    'notifications:read',
    'profile:read','profile:update','profile:change-password',
  ],
  ICT_SUPPORT: [
    'users:read','users:deactivate',
    'students:read','students:import',
    'departments:read','departments:update',
    'courses:read','courses:update',
    'settings:view','settings:update',
    'audit:view',
    'notifications:send','notifications:read',
    'backup:create','backup:restore',
    'profile:read','profile:update','profile:avatar','profile:change-password',
  ],
};
